name: CI/CD Pipeline

# Trigger the workflow on push and pull requests to main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # Job 1: Run Tests (Continuous Integration)
  test:
    runs-on: ubuntu-latest
    
    steps:
    # Checkout the code
    - name: Checkout code
      uses: actions/checkout@v4
    
    # Set up Python
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    # Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install -r requirements.txt
    
    # Run tests
    - name: Run tests with pytest
      run: |
        pytest tests/ -v
      env:
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        SESSION_SECRET: test_secret_for_ci
    
    # Check code style (optional)
    - name: Check code formatting
      run: |
        pip install black
        black --check --diff .
      continue-on-error: true

  # Job 2: Security Check
  security:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install safety
      run: pip install safety
    
    - name: Check for security vulnerabilities
      run: |
        pip install -r requirements.txt
        safety check
      continue-on-error: true

  # Job 3: Deploy (Continuous Deployment)
  deploy:
    needs: [test, security]  # Only run if tests pass
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Deploy to Render
      run: |
        echo "🚀 Deploying to Render..."
        echo "Render will automatically deploy when detecting changes to main branch"
        echo "Your app URL: https://legal-document-demystifier.onrender.com"
    
    - name: Deployment Success
      run: |
        echo "✅ Deployment completed successfully!"
        echo "🎉 Your Legal Document Demystifier is now live!"