name: Code Quality Check

# Run on pull requests to maintain code quality
on:
  pull_request:
    branches: [ main ]

jobs:
  code-quality:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 black isort
        pip install -r requirements.txt
    
    # Check code formatting with Black
    - name: Check code formatting with Black
      run: black --check --diff .
      continue-on-error: true
    
    # Check import sorting
    - name: Check import sorting with isort
      run: isort --check-only --diff .
      continue-on-error: true
    
    # Lint with flake8
    - name: Lint with flake8
      run: |
        # Stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # Exit-zero treats all errors as warnings
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=100 --statistics
      continue-on-error: true
    
    - name: Code Quality Summary
      run: |
        echo "📊 Code Quality Check Complete!"
        echo "Check the logs above for any formatting or style suggestions."